-- Water Business Management Schema (PostgreSQL)
-- Generated from frontend module structure (customers/products/stock/payments/vendors/etc.)
--
-- Notes:
-- - Uses bigint identity PKs and snake_case naming.
-- - Stores money as numeric(12,2).
-- - Stock is movement-based with warehouse + per-employee locations and FILLED/EMPTY states.

BEGIN;

-- Case-insensitive usernames (optional but handy)
CREATE EXTENSION IF NOT EXISTS citext;

-- Updated-at trigger helper
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- =========================
-- Identity & access
-- =========================

CREATE TABLE roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username citext NOT NULL UNIQUE,
  password_hash text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_roles (
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id bigint NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, -- e.g. EMP-001
  name text NOT NULL,
  contact text,
  designation text NOT NULL CHECK (designation IN ('SALESMAN', 'DRIVER', 'OFFICE_STAFF', 'OTHER')),
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  user_id bigint UNIQUE REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_employees_designation ON employees (designation);
CREATE INDEX idx_employees_status ON employees (status);

CREATE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Settings: areas, banks
-- =========================

CREATE TABLE areas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_areas_status ON areas (status);

CREATE TRIGGER trg_areas_updated_at
BEFORE UPDATE ON areas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE employee_areas (
  employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  area_id bigint NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (employee_id, area_id)
);

CREATE TABLE banks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  account_number text NOT NULL,
  branch text,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (name, account_number)
);

CREATE INDEX idx_banks_status ON banks (status);

CREATE TRIGGER trg_banks_updated_at
BEFORE UPDATE ON banks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Parties: customers, vendors
-- =========================

CREATE TABLE customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, -- e.g. CUST-001
  name text NOT NULL,
  contact text,
  address text,
  area_id bigint REFERENCES areas(id) ON DELETE SET NULL,
  -- Optional default salesman (UI selects salesman on invoice; assign-areas exists too)
  default_salesman_employee_id bigint REFERENCES employees(id) ON DELETE SET NULL,
  delivery_days text, -- UI uses free-text like "Mon, Wed, Fri"
  required_bottles integer NOT NULL DEFAULT 0 CHECK (required_bottles >= 0),
  opening_balance numeric(12,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_customers_area_id ON customers (area_id);
CREATE INDEX idx_customers_status ON customers (status);
CREATE INDEX idx_customers_default_salesman ON customers (default_salesman_employee_id);

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE customer_credentials (
  customer_id bigint PRIMARY KEY REFERENCES customers(id) ON DELETE CASCADE,
  username citext NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_customer_credentials_updated_at
BEFORE UPDATE ON customer_credentials
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE vendors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, -- e.g. VEND-001
  name text NOT NULL,
  contact text,
  address text,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_vendors_status ON vendors (status);

CREATE TRIGGER trg_vendors_updated_at
BEFORE UPDATE ON vendors
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Products & pricing
-- =========================

CREATE TABLE product_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_categories_status ON product_categories (status);

CREATE TRIGGER trg_product_categories_updated_at
BEFORE UPDATE ON product_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE, -- optional SKU
  name text NOT NULL UNIQUE,
  category_id bigint REFERENCES product_categories(id) ON DELETE SET NULL,
  bottle_type text, -- e.g. "19 Ltr Bottle", "Disposable Bottle", "Accessories"
  is_returnable boolean NOT NULL DEFAULT false, -- returnable container/empties tracking
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_status ON products (status);

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE product_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  price numeric(12,2) NOT NULL CHECK (price >= 0),
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_to IS NULL OR effective_to > effective_from),
  UNIQUE (product_id, effective_from)
);

CREATE INDEX idx_product_prices_product_id ON product_prices (product_id);
CREATE INDEX idx_product_prices_effective_from ON product_prices (effective_from);

CREATE TRIGGER trg_product_prices_updated_at
BEFORE UPDATE ON product_prices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE customer_product_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  price numeric(12,2) NOT NULL CHECK (price >= 0),
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_to IS NULL OR effective_to > effective_from),
  UNIQUE (customer_id, product_id, effective_from)
);

CREATE INDEX idx_customer_product_prices_customer_id ON customer_product_prices (customer_id);
CREATE INDEX idx_customer_product_prices_product_id ON customer_product_prices (product_id);

CREATE TRIGGER trg_customer_product_prices_updated_at
BEFORE UPDATE ON customer_product_prices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Sales (invoices/bills)
-- =========================

CREATE TABLE sales_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no text NOT NULL UNIQUE, -- e.g. INV-001
  bill_no text, -- e.g. BILL-001 (if distinct)
  bill_book_no text, -- UI: "Bill Book #"
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  salesman_employee_id bigint REFERENCES employees(id) ON DELETE SET NULL,
  order_date date NOT NULL,
  status text NOT NULL DEFAULT 'POSTED' CHECK (status IN ('DRAFT', 'POSTED', 'CANCELLED')),
  subtotal_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0),
  discount_tax_amount numeric(12,2) NOT NULL DEFAULT 0, -- +tax or -discount; keep sign flexible
  total_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  remarks text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sales_invoices_customer_date ON sales_invoices (customer_id, order_date);
CREATE INDEX idx_sales_invoices_salesman_date ON sales_invoices (salesman_employee_id, order_date);
CREATE INDEX idx_sales_invoices_order_date ON sales_invoices (order_date);
CREATE INDEX idx_sales_invoices_status ON sales_invoices (status);

CREATE TRIGGER trg_sales_invoices_updated_at
BEFORE UPDATE ON sales_invoices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE sales_invoice_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
  line_no integer NOT NULL,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
  sale_qty integer NOT NULL DEFAULT 0 CHECK (sale_qty >= 0),
  return_qty integer NOT NULL DEFAULT 0 CHECK (return_qty >= 0),
  line_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (line_amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (invoice_id, line_no)
);

CREATE INDEX idx_sales_invoice_items_invoice_id ON sales_invoice_items (invoice_id);
CREATE INDEX idx_sales_invoice_items_product_id ON sales_invoice_items (product_id);

CREATE TRIGGER trg_sales_invoice_items_updated_at
BEFORE UPDATE ON sales_invoice_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Customer payments & deposits
-- =========================

CREATE TABLE customer_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  receiver_employee_id bigint REFERENCES employees(id) ON DELETE SET NULL, -- Payment Receiver
  payment_date date NOT NULL,
  method text NOT NULL CHECK (method IN ('CASH', 'BANK', 'CHEQUE')),
  bank_id bigint REFERENCES banks(id) ON DELETE SET NULL,
  cheque_no text,
  payment_mode text, -- UI: Daily Cash etc. (free-form)
  received_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (received_amount >= 0),
  discount_tax_amount numeric(12,2) NOT NULL DEFAULT 0,
  remarks text,
  status text NOT NULL DEFAULT 'POSTED' CHECK (status IN ('POSTED', 'VOID')),
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (method = 'CASH' AND bank_id IS NULL AND cheque_no IS NULL)
    OR (method = 'BANK' AND bank_id IS NOT NULL)
    OR (method = 'CHEQUE' AND cheque_no IS NOT NULL)
  )
);


CREATE INDEX idx_customer_payments_customer_date ON customer_payments (customer_id, payment_date);
CREATE INDEX idx_customer_payments_receiver_date ON customer_payments (receiver_employee_id, payment_date);
CREATE INDEX idx_customer_payments_status ON customer_payments (status);

CREATE TRIGGER trg_customer_payments_updated_at
BEFORE UPDATE ON customer_payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Optional: allocate payments across invoices (enables invoice-wise outstanding)
CREATE TABLE customer_payment_allocations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id bigint NOT NULL REFERENCES customer_payments(id) ON DELETE CASCADE,
  invoice_id bigint NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
  allocated_amount numeric(12,2) NOT NULL CHECK (allocated_amount > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (payment_id, invoice_id)
);

CREATE INDEX idx_customer_payment_allocations_invoice_id ON customer_payment_allocations (invoice_id);

CREATE TABLE customer_security_deposits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  deposit_date date NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  remarks text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_security_deposits_customer_date ON customer_security_deposits (customer_id, deposit_date);

CREATE TRIGGER trg_customer_security_deposits_updated_at
BEFORE UPDATE ON customer_security_deposits
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE customer_security_refunds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  refund_date date NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  remarks text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_security_refunds_customer_date ON customer_security_refunds (customer_id, refund_date);

CREATE TRIGGER trg_customer_security_refunds_updated_at
BEFORE UPDATE ON customer_security_refunds
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Vendor purchases & payments
-- =========================

CREATE TABLE vendor_purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id bigint NOT NULL REFERENCES vendors(id) ON DELETE RESTRICT,
  purchase_date date NOT NULL,
  status text NOT NULL DEFAULT 'POSTED' CHECK (status IN ('DRAFT', 'POSTED', 'CANCELLED')),
  subtotal_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0),
  total_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  remarks text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_vendor_purchases_vendor_date ON vendor_purchases (vendor_id, purchase_date);
CREATE INDEX idx_vendor_purchases_status ON vendor_purchases (status);

CREATE TRIGGER trg_vendor_purchases_updated_at
BEFORE UPDATE ON vendor_purchases
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE vendor_purchase_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id bigint NOT NULL REFERENCES vendor_purchases(id) ON DELETE CASCADE,
  line_no integer NOT NULL,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  qty integer NOT NULL DEFAULT 0 CHECK (qty >= 0),
  rate numeric(12,2) NOT NULL DEFAULT 0 CHECK (rate >= 0),
  line_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (line_amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (purchase_id, line_no)
);

CREATE INDEX idx_vendor_purchase_items_purchase_id ON vendor_purchase_items (purchase_id);
CREATE INDEX idx_vendor_purchase_items_product_id ON vendor_purchase_items (product_id);

CREATE TRIGGER trg_vendor_purchase_items_updated_at
BEFORE UPDATE ON vendor_purchase_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE vendor_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id bigint NOT NULL REFERENCES vendors(id) ON DELETE RESTRICT,
  payment_date date NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  remarks text,
  status text NOT NULL DEFAULT 'POSTED' CHECK (status IN ('POSTED', 'VOID')),
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_vendor_payments_vendor_date ON vendor_payments (vendor_id, payment_date);
CREATE INDEX idx_vendor_payments_status ON vendor_payments (status);

CREATE TRIGGER trg_vendor_payments_updated_at
BEFORE UPDATE ON vendor_payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Optional: allocate vendor payments to purchases
CREATE TABLE vendor_payment_allocations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_payment_id bigint NOT NULL REFERENCES vendor_payments(id) ON DELETE CASCADE,
  vendor_purchase_id bigint NOT NULL REFERENCES vendor_purchases(id) ON DELETE CASCADE,
  allocated_amount numeric(12,2) NOT NULL CHECK (allocated_amount > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (vendor_payment_id, vendor_purchase_id)
);

CREATE INDEX idx_vendor_payment_allocations_purchase_id ON vendor_payment_allocations (vendor_purchase_id);

-- =========================
-- Stock (warehouse + per-employee)
-- =========================

CREATE TABLE stock_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, -- e.g. WH-001, EMP-001, DMG-001
  name text NOT NULL,
  location_type text NOT NULL CHECK (location_type IN ('WAREHOUSE', 'EMPLOYEE', 'DAMAGED', 'OTHER')),
  employee_id bigint REFERENCES employees(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- One location per employee (for EMPLOYEE type)
CREATE UNIQUE INDEX ux_stock_locations_employee
ON stock_locations (employee_id)
WHERE location_type = 'EMPLOYEE' AND employee_id IS NOT NULL;

-- Enforce a single warehouse location (convention)
CREATE UNIQUE INDEX ux_stock_locations_one_warehouse
ON stock_locations (location_type)
WHERE location_type = 'WAREHOUSE';

CREATE INDEX idx_stock_locations_type ON stock_locations (location_type);
CREATE INDEX idx_stock_locations_status ON stock_locations (status);

CREATE TRIGGER trg_stock_locations_updated_at
BEFORE UPDATE ON stock_locations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_on date NOT NULL,
  movement_type text NOT NULL CHECK (movement_type IN (
    'FILLING',     -- EMPTY -> FILLED in warehouse (or similar conversion)
    'DAMAGE',      -- move into damaged location / write-off
    'IN',          -- generic move into an account/location
    'OUT',         -- generic move out of an account/location
    'RETURN',      -- returns (often empties)
    'SALE',        -- linked to sales invoice
    'PURCHASE',    -- linked to vendor purchase
    'ADJUST'       -- manual adjustment
  )),
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  qty integer NOT NULL CHECK (qty > 0),
  from_location_id bigint REFERENCES stock_locations(id) ON DELETE SET NULL,
  to_location_id bigint REFERENCES stock_locations(id) ON DELETE SET NULL,
  from_state text NOT NULL DEFAULT 'NA' CHECK (from_state IN ('FILLED', 'EMPTY', 'NA')),
  to_state text NOT NULL DEFAULT 'NA' CHECK (to_state IN ('FILLED', 'EMPTY', 'NA')),
  remarks text,
  -- Optional document linkage for traceability
  sales_invoice_id bigint REFERENCES sales_invoices(id) ON DELETE SET NULL,
  vendor_purchase_id bigint REFERENCES vendor_purchases(id) ON DELETE SET NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (from_location_id IS NOT NULL OR to_location_id IS NOT NULL)
);

CREATE INDEX idx_stock_movements_occurred_on ON stock_movements (occurred_on);
CREATE INDEX idx_stock_movements_product_id ON stock_movements (product_id);
CREATE INDEX idx_stock_movements_from_location ON stock_movements (from_location_id);
CREATE INDEX idx_stock_movements_to_location ON stock_movements (to_location_id);
CREATE INDEX idx_stock_movements_sales_invoice_id ON stock_movements (sales_invoice_id);
CREATE INDEX idx_stock_movements_vendor_purchase_id ON stock_movements (vendor_purchase_id);
CREATE INDEX idx_stock_movements_type ON stock_movements (movement_type);

CREATE TRIGGER trg_stock_movements_updated_at
BEFORE UPDATE ON stock_movements
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Expenditure
-- =========================

CREATE TABLE expense_heads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_expense_heads_status ON expense_heads (status);

CREATE TRIGGER trg_expense_heads_updated_at
BEFORE UPDATE ON expense_heads
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  head_id bigint NOT NULL REFERENCES expense_heads(id) ON DELETE RESTRICT,
  expense_date date NOT NULL,
  description text,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_expenses_head_date ON expenses (head_id, expense_date);
CREATE INDEX idx_expenses_expense_date ON expenses (expense_date);

CREATE TRIGGER trg_expenses_updated_at
BEFORE UPDATE ON expenses
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;

